# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/proto/common.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'common/proto/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63ommon/proto/common.proto\x12\x06\x63ommon\"q\n\x08PidStats\x12\x0b\n\x03pid\x18\x01 \x01(\x05\x12\x12\n\ncpuPercent\x18\x02 \x01(\x01\x12\r\n\x05rssKb\x18\x03 \x01(\x04\x12\x12\n\nreadKbPerS\x18\x04 \x01(\x04\x12\x13\n\x0bwriteKbPerS\x18\x05 \x01(\x04\x12\x0c\n\x04\x63omm\x18\x06 \x01(\t\"3\n\x04\x46ile\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x12\x0c\n\x04size\x18\x03 \x01(\x03\"\xa5\x01\n\tCosConfig\x12\x10\n\x08\x65ndpoint\x18\x01 \x01(\t\x12\x13\n\x0b\x61\x63\x63\x65ssKeyId\x18\x02 \x01(\t\x12\x17\n\x0fsecretAccessKey\x18\x03 \x01(\t\x12\x0e\n\x06\x62ucket\x18\x04 \x01(\t\x12\x0e\n\x06region\x18\x05 \x01(\t\x12\x14\n\x0csessionToken\x18\x06 \x01(\t\x12\x12\n\nexpireTime\x18\x07 \x01(\x03\x12\x0e\n\x06useSsl\x18\x08 \x01(\x08\x42-Z+github.com/mini-drop/apiserver/proto/commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.proto.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/mini-drop/apiserver/proto/common'
  _globals['_PIDSTATS']._serialized_start=37
  _globals['_PIDSTATS']._serialized_end=150
  _globals['_FILE']._serialized_start=152
  _globals['_FILE']._serialized_end=203
  _globals['_COSCONFIG']._serialized_start=206
  _globals['_COSCONFIG']._serialized_end=371
# @@protoc_insertion_point(module_scope)
