# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from common.proto import control_pb2 as common_dot_proto_dot_control__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in common/proto/control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlStub:
    """----------------------------------------------------------
    Control 服务：API 后台 → Drop Server 的指挥接口
    ----------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTask = channel.unary_unary(
                '/control.Control/CreateTask',
                request_serializer=common_dot_proto_dot_control__pb2.CreateTaskRequest.SerializeToString,
                response_deserializer=common_dot_proto_dot_control__pb2.CreateTaskResponse.FromString,
                _registered_method=True)
        self.FetchData = channel.unary_unary(
                '/control.Control/FetchData',
                request_serializer=common_dot_proto_dot_control__pb2.FetchDataRequest.SerializeToString,
                response_deserializer=common_dot_proto_dot_control__pb2.FetchDataResponse.FromString,
                _registered_method=True)
        self.StatAgent = channel.unary_unary(
                '/control.Control/StatAgent',
                request_serializer=common_dot_proto_dot_control__pb2.StatAgentRequest.SerializeToString,
                response_deserializer=common_dot_proto_dot_control__pb2.StatAgentResponse.FromString,
                _registered_method=True)


class ControlServicer:
    """----------------------------------------------------------
    Control 服务：API 后台 → Drop Server 的指挥接口
    ----------------------------------------------------------
    """

    def CreateTask(self, request, context):
        """CreateTask：创建一个新采集任务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchData(self, request, context):
        """FetchData：获取某个任务的结果数据
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StatAgent(self, request, context):
        """StatAgent：查询某台机器上 Agent 的资源占用情况
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=common_dot_proto_dot_control__pb2.CreateTaskRequest.FromString,
                    response_serializer=common_dot_proto_dot_control__pb2.CreateTaskResponse.SerializeToString,
            ),
            'FetchData': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchData,
                    request_deserializer=common_dot_proto_dot_control__pb2.FetchDataRequest.FromString,
                    response_serializer=common_dot_proto_dot_control__pb2.FetchDataResponse.SerializeToString,
            ),
            'StatAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.StatAgent,
                    request_deserializer=common_dot_proto_dot_control__pb2.StatAgentRequest.FromString,
                    response_serializer=common_dot_proto_dot_control__pb2.StatAgentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'control.Control', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('control.Control', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Control:
    """----------------------------------------------------------
    Control 服务：API 后台 → Drop Server 的指挥接口
    ----------------------------------------------------------
    """

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control.Control/CreateTask',
            common_dot_proto_dot_control__pb2.CreateTaskRequest.SerializeToString,
            common_dot_proto_dot_control__pb2.CreateTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control.Control/FetchData',
            common_dot_proto_dot_control__pb2.FetchDataRequest.SerializeToString,
            common_dot_proto_dot_control__pb2.FetchDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StatAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control.Control/StatAgent',
            common_dot_proto_dot_control__pb2.StatAgentRequest.SerializeToString,
            common_dot_proto_dot_control__pb2.StatAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
