# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/proto/control.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'common/proto/control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.proto import hotmethod_pb2 as common_dot_proto_dot_hotmethod__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63ommon/proto/control.proto\x12\x07\x63ontrol\x1a\x1c\x63ommon/proto/hotmethod.proto\"]\n\x11\x43reateTaskRequest\x12\x10\n\x08targetIP\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\x12%\n\x08taskDesc\x18\x03 \x01(\x0b\x32\x13.hotmethod.TaskDesc\"?\n\x12\x43reateTaskResponse\x12\x0e\n\x06taskID\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\t\"4\n\x10\x46\x65tchDataRequest\x12\x10\n\x08targetIP\x18\x01 \x01(\t\x12\x0e\n\x06taskID\x18\x02 \x01(\t\"<\n\x11\x46\x65tchDataResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"$\n\x10StatAgentRequest\x12\x10\n\x08targetIP\x18\x01 \x01(\t\"}\n\x11StatAgentResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x12\n\ncpuPercent\x18\x03 \x01(\x01\x12\x10\n\x08memoryKb\x18\x04 \x01(\x04\x12\x12\n\nreadKbPerS\x18\x05 \x01(\x04\x12\x13\n\x0bwriteKbPerS\x18\x06 \x01(\x04\x32\xd8\x01\n\x07\x43ontrol\x12\x45\n\nCreateTask\x12\x1a.control.CreateTaskRequest\x1a\x1b.control.CreateTaskResponse\x12\x42\n\tFetchData\x12\x19.control.FetchDataRequest\x1a\x1a.control.FetchDataResponse\x12\x42\n\tStatAgent\x12\x19.control.StatAgentRequest\x1a\x1a.control.StatAgentResponseB.Z,github.com/mini-drop/apiserver/proto/controlb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.proto.control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/mini-drop/apiserver/proto/control'
  _globals['_CREATETASKREQUEST']._serialized_start=69
  _globals['_CREATETASKREQUEST']._serialized_end=162
  _globals['_CREATETASKRESPONSE']._serialized_start=164
  _globals['_CREATETASKRESPONSE']._serialized_end=227
  _globals['_FETCHDATAREQUEST']._serialized_start=229
  _globals['_FETCHDATAREQUEST']._serialized_end=281
  _globals['_FETCHDATARESPONSE']._serialized_start=283
  _globals['_FETCHDATARESPONSE']._serialized_end=343
  _globals['_STATAGENTREQUEST']._serialized_start=345
  _globals['_STATAGENTREQUEST']._serialized_end=381
  _globals['_STATAGENTRESPONSE']._serialized_start=383
  _globals['_STATAGENTRESPONSE']._serialized_end=508
  _globals['_CONTROL']._serialized_start=511
  _globals['_CONTROL']._serialized_end=727
# @@protoc_insertion_point(module_scope)
