# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/proto/healthcheck.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'common/proto/healthcheck.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.proto import common_pb2 as common_dot_proto_dot_common__pb2
from common.proto import hotmethod_pb2 as common_dot_proto_dot_hotmethod__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63ommon/proto/healthcheck.proto\x12\x0bhealthcheck\x1a\x19\x63ommon/proto/common.proto\x1a\x1c\x63ommon/proto/hotmethod.proto\"\xa9\x01\n\x12HealthCheckRequest\x12\x10\n\x08hostName\x18\x01 \x01(\t\x12\x0e\n\x06ipAddr\x18\x02 \x01(\t\x12\x0b\n\x03uid\x18\x03 \x01(\t\x12\x14\n\x0c\x61gentVersion\x18\x04 \x01(\t\x12$\n\nselfPstats\x18\x05 \x01(\x0b\x32\x10.common.PidStats\x12(\n\x0e\x63hildrenPstats\x18\x06 \x01(\x0b\x32\x10.common.PidStats\"\xc9\x01\n\x13HealthCheckResponse\x12>\n\x06status\x18\x01 \x01(\x0e\x32..healthcheck.HealthCheckResponse.ServingStatus\x12\x0f\n\x07pending\x18\x02 \x01(\x08\x12%\n\x08taskDesc\x18\x03 \x01(\x0b\x32\x13.hotmethod.TaskDesc\":\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x32V\n\x0bHealthCheck\x12G\n\x02\x44o\x12\x1f.healthcheck.HealthCheckRequest\x1a .healthcheck.HealthCheckResponseB2Z0github.com/mini-drop/apiserver/proto/healthcheckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.proto.healthcheck_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/mini-drop/apiserver/proto/healthcheck'
  _globals['_HEALTHCHECKREQUEST']._serialized_start=105
  _globals['_HEALTHCHECKREQUEST']._serialized_end=274
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=277
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=478
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_start=420
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_end=478
  _globals['_HEALTHCHECK']._serialized_start=480
  _globals['_HEALTHCHECK']._serialized_end=566
# @@protoc_insertion_point(module_scope)
