# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/proto/hotmethod.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'common/proto/hotmethod.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from common.proto import common_pb2 as common_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63ommon/proto/hotmethod.proto\x12\thotmethod\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19\x63ommon/proto/common.proto\"\xec\x01\n\x08TaskDesc\x12\x0e\n\x06taskID\x18\x01 \x01(\t\x12\x10\n\x08taskType\x18\x02 \x01(\r\x12\x14\n\x0cprofilerType\x18\x03 \x01(\r\x12)\n\nsampleArgv\x18\x04 \x01(\x0b\x32\x15.hotmethod.RecordArgv\x12\x15\n\rcontainerName\x18\x05 \x01(\t\x12\x15\n\rcontainerType\x18\x06 \x01(\r\x12\x12\n\ntimeoutSec\x18\x07 \x01(\r\x12$\n\tcosConfig\x18\x08 \x01(\x0b\x32\x11.common.CosConfig\x12\x15\n\rscriptContent\x18\t \x01(\t\"m\n\nRecordArgv\x12\n\n\x02hz\x18\x01 \x01(\r\x12\x10\n\x08\x64uration\x18\x02 \x01(\x04\x12\x0b\n\x03pid\x18\x03 \x01(\x05\x12\x11\n\tcallgraph\x18\x04 \x01(\t\x12\x12\n\nsubprocess\x18\x05 \x01(\x08\x12\r\n\x05\x65vent\x18\x06 \x01(\t\"\xae\x01\n\nTaskResult\x12\x0e\n\x06taskID\x18\x01 \x01(\t\x12\x14\n\x0c\x65rrorMessage\x18\x02 \x01(\t\x12\x1a\n\x04\x66ile\x18\x03 \x01(\x0b\x32\x0c.common.File\x12\x0e\n\x06\x63osKey\x18\x04 \x01(\t\x12$\n\nselfPstats\x18\x05 \x03(\x0b\x32\x10.common.PidStats\x12(\n\x0e\x63hildrenPstats\x18\x06 \x03(\x0b\x32\x10.common.PidStats\"\x14\n\x06Target\x12\n\n\x02ip\x18\x01 \x01(\t2\x80\x01\n\tHotmethod\x12\x34\n\x07\x43ollect\x12\x11.hotmethod.Target\x1a\x16.google.protobuf.Empty\x12=\n\x0cNotifyResult\x12\x15.hotmethod.TaskResult\x1a\x16.google.protobuf.EmptyB0Z.github.com/mini-drop/apiserver/proto/hotmethodb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.proto.hotmethod_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.github.com/mini-drop/apiserver/proto/hotmethod'
  _globals['_TASKDESC']._serialized_start=100
  _globals['_TASKDESC']._serialized_end=336
  _globals['_RECORDARGV']._serialized_start=338
  _globals['_RECORDARGV']._serialized_end=447
  _globals['_TASKRESULT']._serialized_start=450
  _globals['_TASKRESULT']._serialized_end=624
  _globals['_TARGET']._serialized_start=626
  _globals['_TARGET']._serialized_end=646
  _globals['_HOTMETHOD']._serialized_start=649
  _globals['_HOTMETHOD']._serialized_end=777
# @@protoc_insertion_point(module_scope)
