# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/proto/init.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'common/proto/init.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.proto import common_pb2 as common_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63ommon/proto/init.proto\x12\x06initpb\x1a\x19\x63ommon/proto/common.proto\"[\n\x14RegisterAgentRequest\x12\x10\n\x08hostName\x18\x01 \x01(\t\x12\x0e\n\x06ipAddr\x18\x02 \x01(\t\x12\x0b\n\x03uid\x18\x03 \x01(\t\x12\x14\n\x0c\x61gentVersion\x18\x04 \x01(\t\"2\n\x15RegisterAgentResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\"!\n\x12\x46\x65tchConfigRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\"V\n\x13\x46\x65tchConfigResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12$\n\tcosConfig\x18\x03 \x01(\x0b\x32\x11.common.CosConfig2\xa5\x01\n\rInitAgentInfo\x12L\n\rRegisterAgent\x12\x1c.initpb.RegisterAgentRequest\x1a\x1d.initpb.RegisterAgentResponse\x12\x46\n\x0b\x46\x65tchConfig\x12\x1a.initpb.FetchConfigRequest\x1a\x1b.initpb.FetchConfigResponseB-Z+github.com/mini-drop/apiserver/proto/initpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.proto.init_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/mini-drop/apiserver/proto/initpb'
  _globals['_REGISTERAGENTREQUEST']._serialized_start=62
  _globals['_REGISTERAGENTREQUEST']._serialized_end=153
  _globals['_REGISTERAGENTRESPONSE']._serialized_start=155
  _globals['_REGISTERAGENTRESPONSE']._serialized_end=205
  _globals['_FETCHCONFIGREQUEST']._serialized_start=207
  _globals['_FETCHCONFIGREQUEST']._serialized_end=240
  _globals['_FETCHCONFIGRESPONSE']._serialized_start=242
  _globals['_FETCHCONFIGRESPONSE']._serialized_end=328
  _globals['_INITAGENTINFO']._serialized_start=331
  _globals['_INITAGENTINFO']._serialized_end=496
# @@protoc_insertion_point(module_scope)
