# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from common.proto import init_pb2 as common_dot_proto_dot_init__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in common/proto/init_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InitAgentInfoStub:
    """----------------------------------------------------------
    InitAgentInfo 服务：Agent 启动时调用
    ----------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAgent = channel.unary_unary(
                '/initpb.InitAgentInfo/RegisterAgent',
                request_serializer=common_dot_proto_dot_init__pb2.RegisterAgentRequest.SerializeToString,
                response_deserializer=common_dot_proto_dot_init__pb2.RegisterAgentResponse.FromString,
                _registered_method=True)
        self.FetchConfig = channel.unary_unary(
                '/initpb.InitAgentInfo/FetchConfig',
                request_serializer=common_dot_proto_dot_init__pb2.FetchConfigRequest.SerializeToString,
                response_deserializer=common_dot_proto_dot_init__pb2.FetchConfigResponse.FromString,
                _registered_method=True)


class InitAgentInfoServicer:
    """----------------------------------------------------------
    InitAgentInfo 服务：Agent 启动时调用
    ----------------------------------------------------------
    """

    def RegisterAgent(self, request, context):
        """RegisterAgent：Agent 向 Server 报到
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchConfig(self, request, context):
        """FetchConfig：获取配置（主要是对象存储的钥匙）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InitAgentInfoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=common_dot_proto_dot_init__pb2.RegisterAgentRequest.FromString,
                    response_serializer=common_dot_proto_dot_init__pb2.RegisterAgentResponse.SerializeToString,
            ),
            'FetchConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchConfig,
                    request_deserializer=common_dot_proto_dot_init__pb2.FetchConfigRequest.FromString,
                    response_serializer=common_dot_proto_dot_init__pb2.FetchConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'initpb.InitAgentInfo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('initpb.InitAgentInfo', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InitAgentInfo:
    """----------------------------------------------------------
    InitAgentInfo 服务：Agent 启动时调用
    ----------------------------------------------------------
    """

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/initpb.InitAgentInfo/RegisterAgent',
            common_dot_proto_dot_init__pb2.RegisterAgentRequest.SerializeToString,
            common_dot_proto_dot_init__pb2.RegisterAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/initpb.InitAgentInfo/FetchConfig',
            common_dot_proto_dot_init__pb2.FetchConfigRequest.SerializeToString,
            common_dot_proto_dot_init__pb2.FetchConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
