// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: common/proto/init.proto

package initpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InitAgentInfoClient is the client API for InitAgentInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InitAgentInfoClient interface {
	RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error)
	FetchConfig(ctx context.Context, in *FetchConfigRequest, opts ...grpc.CallOption) (*FetchConfigResponse, error)
}

type initAgentInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewInitAgentInfoClient(cc grpc.ClientConnInterface) InitAgentInfoClient {
	return &initAgentInfoClient{cc}
}

func (c *initAgentInfoClient) RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error) {
	out := new(RegisterAgentResponse)
	err := c.cc.Invoke(ctx, "/initpb.InitAgentInfo/RegisterAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *initAgentInfoClient) FetchConfig(ctx context.Context, in *FetchConfigRequest, opts ...grpc.CallOption) (*FetchConfigResponse, error) {
	out := new(FetchConfigResponse)
	err := c.cc.Invoke(ctx, "/initpb.InitAgentInfo/FetchConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InitAgentInfoServer is the server API for InitAgentInfo service.
// All implementations must embed UnimplementedInitAgentInfoServer
// for forward compatibility
type InitAgentInfoServer interface {
	RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error)
	FetchConfig(context.Context, *FetchConfigRequest) (*FetchConfigResponse, error)
	mustEmbedUnimplementedInitAgentInfoServer()
}

// UnimplementedInitAgentInfoServer must be embedded to have forward compatible implementations.
type UnimplementedInitAgentInfoServer struct {
}

func (UnimplementedInitAgentInfoServer) RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedInitAgentInfoServer) FetchConfig(context.Context, *FetchConfigRequest) (*FetchConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchConfig not implemented")
}
func (UnimplementedInitAgentInfoServer) mustEmbedUnimplementedInitAgentInfoServer() {}

// UnsafeInitAgentInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InitAgentInfoServer will
// result in compilation errors.
type UnsafeInitAgentInfoServer interface {
	mustEmbedUnimplementedInitAgentInfoServer()
}

func RegisterInitAgentInfoServer(s grpc.ServiceRegistrar, srv InitAgentInfoServer) {
	s.RegisterService(&InitAgentInfo_ServiceDesc, srv)
}

func _InitAgentInfo_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitAgentInfoServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/initpb.InitAgentInfo/RegisterAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitAgentInfoServer).RegisterAgent(ctx, req.(*RegisterAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InitAgentInfo_FetchConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitAgentInfoServer).FetchConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/initpb.InitAgentInfo/FetchConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitAgentInfoServer).FetchConfig(ctx, req.(*FetchConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InitAgentInfo_ServiceDesc is the grpc.ServiceDesc for InitAgentInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InitAgentInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "initpb.InitAgentInfo",
	HandlerType: (*InitAgentInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _InitAgentInfo_RegisterAgent_Handler,
		},
		{
			MethodName: "FetchConfig",
			Handler:    _InitAgentInfo_FetchConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/proto/init.proto",
}
