syntax = "proto3";

package parca.query.v1alpha1;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/mini-drop/apiserver/proto/parca/query/v1alpha1;parcapb";

service QueryService {
  rpc ProfileTypes(ProfileTypesRequest) returns (ProfileTypesResponse);
  rpc Query(QueryRequest) returns (QueryResponse);
  rpc Labels(LabelsRequest) returns (LabelsResponse);
  rpc Values(ValuesRequest) returns (ValuesResponse);
}

message ProfileTypesRequest {
  google.protobuf.Timestamp start = 1;
  google.protobuf.Timestamp end = 2;
}

message ProfileTypesResponse {
  repeated ProfileType types = 1;
}

message ProfileType {
  string name = 1;
  string sample_type = 2;
  string sample_unit = 3;
  string period_type = 4;
  string period_unit = 5;
  bool delta = 6;
}

message QueryRequest {
  enum Mode {
    MODE_SINGLE_UNSPECIFIED = 0;
    MODE_DIFF = 1;
    MODE_MERGE = 2;
  }
  enum ReportType {
    REPORT_TYPE_FLAMEGRAPH_UNSPECIFIED = 0;
    REPORT_TYPE_PPROF = 1;
    REPORT_TYPE_TOP = 2;
    REPORT_TYPE_CALLGRAPH = 3;
    REPORT_TYPE_FLAMEGRAPH_TABLE = 4;
    REPORT_TYPE_FLAMEGRAPH_ARROW = 5;
    REPORT_TYPE_SOURCE = 6;
    REPORT_TYPE_TABLE_ARROW = 7;
    REPORT_TYPE_PROFILE_METADATA = 8;
    REPORT_TYPE_FLAMECHART = 9;
  }
  Mode mode = 1;
  oneof options {
    MergeProfile merge = 3;
    SingleProfile single = 4;
  }
  ReportType report_type = 5;
  float node_trim_threshold = 7;
}

message MergeProfile {
  string query = 1;
  google.protobuf.Timestamp start = 2;
  google.protobuf.Timestamp end = 3;
}

message SingleProfile {
  google.protobuf.Timestamp time = 1;
  string query = 2;
}

message QueryResponse {
  oneof report {
    Flamegraph flamegraph = 5;
    Top top = 7;
  }
  int64 total = 9;
  int64 filtered = 10;
}

message Flamegraph {
  FlamegraphRootNode root = 1;
  int64 total = 2;
  string unit = 3;
  int32 height = 4;
  repeated string string_table = 5;
  repeated Location locations = 6;
  repeated Mapping mapping = 7;
  repeated Function function = 8;
  int64 untrimmed_total = 9;
  int64 trimmed = 10;
}

message FlamegraphRootNode {
  int64 cumulative = 1;
  int64 diff = 2;
  repeated FlamegraphNode children = 3;
}

message FlamegraphNode {
  TopNodeMeta meta = 1;
  int64 cumulative = 2;
  int64 diff = 3;
  repeated FlamegraphNode children = 4;
}

message Top {
  repeated TopNode list = 1;
  int32 reported = 2;
  int32 total = 3;
  string unit = 4;
}

message TopNode {
  TopNodeMeta meta = 1;
  int64 cumulative = 2;
  int64 flat = 3;
  int64 diff = 4;
}

message TopNodeMeta {
  Mapping mapping = 2;
  Function function = 3;
  uint32 location_index = 5;
  uint32 line_index = 6;
}

message Function {
  string id = 1;
  int64 start_line = 2;
  string name = 3;
  string system_name = 4;
  string filename = 5;
  uint32 name_string_index = 6;
  uint32 system_name_string_index = 7;
  uint32 filename_string_index = 8;
}

message Mapping {
  string file = 5;
  uint32 file_string_index = 11;
}

message Location {
  string id = 1;
  uint64 address = 2;
  string mapping_id = 4;
  bool is_folded = 5;
  repeated Line lines = 6;
  uint32 mapping_index = 7;
}

message Line {
  string function_id = 1;
  int64 line = 2;
  uint32 function_index = 3;
}

message LabelsRequest {
  repeated string match = 1;
  google.protobuf.Timestamp start = 2;
  google.protobuf.Timestamp end = 3;
  string profile_type = 4;
}

message LabelsResponse {
  repeated string label_names = 1;
  repeated string warnings = 2;
}

message ValuesRequest {
  string label_name = 1;
  repeated string match = 2;
  google.protobuf.Timestamp start = 3;
  google.protobuf.Timestamp end = 4;
  string profile_type = 5;
}

message ValuesResponse {
  repeated string label_values = 1;
  repeated string warnings = 2;
}
