// ============================================================
// common.proto — 通用数据结构
// ============================================================
// 小白理解：就像 C 语言的 .h 头文件，定义"结构体"
// 其他 proto 文件可以 import 这个文件来复用这些结构
// ============================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: common/proto/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ----------------------------------------------------------
// PidStats：进程的资源占用情况
// 类似 Linux 的 top 命令看到的信息
// ----------------------------------------------------------
type PidStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid         int32   `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`                 // 进程 ID
	CpuPercent  float64 `protobuf:"fixed64,2,opt,name=cpuPercent,proto3" json:"cpuPercent,omitempty"`  // CPU 使用率，比如 45.5 表示 45.5%
	RssKb       uint64  `protobuf:"varint,3,opt,name=rssKb,proto3" json:"rssKb,omitempty"`             // 物理内存占用（KB）
	ReadKbPerS  uint64  `protobuf:"varint,4,opt,name=readKbPerS,proto3" json:"readKbPerS,omitempty"`   // 每秒从磁盘读了多少 KB
	WriteKbPerS uint64  `protobuf:"varint,5,opt,name=writeKbPerS,proto3" json:"writeKbPerS,omitempty"` // 每秒往磁盘写了多少 KB
	Comm        string  `protobuf:"bytes,6,opt,name=comm,proto3" json:"comm,omitempty"`                // 进程名字，比如 "nginx"
}

func (x *PidStats) Reset() {
	*x = PidStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PidStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PidStats) ProtoMessage() {}

func (x *PidStats) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PidStats.ProtoReflect.Descriptor instead.
func (*PidStats) Descriptor() ([]byte, []int) {
	return file_common_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *PidStats) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *PidStats) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *PidStats) GetRssKb() uint64 {
	if x != nil {
		return x.RssKb
	}
	return 0
}

func (x *PidStats) GetReadKbPerS() uint64 {
	if x != nil {
		return x.ReadKbPerS
	}
	return 0
}

func (x *PidStats) GetWriteKbPerS() uint64 {
	if x != nil {
		return x.WriteKbPerS
	}
	return 0
}

func (x *PidStats) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

// ----------------------------------------------------------
// AttemptStatus：Agent 心跳里汇报的执行尝试
// ----------------------------------------------------------
type AttemptStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskID    string `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
	AttemptId uint64 `protobuf:"varint,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
}

func (x *AttemptStatus) Reset() {
	*x = AttemptStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttemptStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttemptStatus) ProtoMessage() {}

func (x *AttemptStatus) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttemptStatus.ProtoReflect.Descriptor instead.
func (*AttemptStatus) Descriptor() ([]byte, []int) {
	return file_common_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *AttemptStatus) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *AttemptStatus) GetAttemptId() uint64 {
	if x != nil {
		return x.AttemptId
	}
	return 0
}

// ----------------------------------------------------------
// File：文件描述（传输小文件用）
// ----------------------------------------------------------
type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // 文件名，比如 "perf.data"
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // 文件的二进制内容
	Size    int64  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`      // 文件大小（字节）
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_common_proto_common_proto_rawDescGZIP(), []int{2}
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *File) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// ----------------------------------------------------------
// CosConfig：对象存储（MinIO/COS）的连接信息
// 就像是一把"临时钥匙"，让 Agent 知道上传到哪里
// ----------------------------------------------------------
type CosConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Endpoint        string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`               // 存储服务地址，比如 "minio:9000"
	AccessKeyId     string `protobuf:"bytes,2,opt,name=accessKeyId,proto3" json:"accessKeyId,omitempty"`         // 用户名
	SecretAccessKey string `protobuf:"bytes,3,opt,name=secretAccessKey,proto3" json:"secretAccessKey,omitempty"` // 密码
	Bucket          string `protobuf:"bytes,4,opt,name=bucket,proto3" json:"bucket,omitempty"`                   // 存储桶名（相当于文件夹）
	Region          string `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`                   // 区域（MinIO 可以不填）
	SessionToken    string `protobuf:"bytes,6,opt,name=sessionToken,proto3" json:"sessionToken,omitempty"`       // 临时令牌（提高安全性）
	ExpireTime      int64  `protobuf:"varint,7,opt,name=expireTime,proto3" json:"expireTime,omitempty"`          // 过期时间
	UseSsl          bool   `protobuf:"varint,8,opt,name=useSsl,proto3" json:"useSsl,omitempty"`                  // 是否用 HTTPS
}

func (x *CosConfig) Reset() {
	*x = CosConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CosConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosConfig) ProtoMessage() {}

func (x *CosConfig) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosConfig.ProtoReflect.Descriptor instead.
func (*CosConfig) Descriptor() ([]byte, []int) {
	return file_common_proto_common_proto_rawDescGZIP(), []int{3}
}

func (x *CosConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *CosConfig) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *CosConfig) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

func (x *CosConfig) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *CosConfig) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CosConfig) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *CosConfig) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *CosConfig) GetUseSsl() bool {
	if x != nil {
		return x.UseSsl
	}
	return false
}

var File_common_proto_common_proto protoreflect.FileDescriptor

var file_common_proto_common_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x22, 0xa8, 0x01, 0x0a, 0x08, 0x50, 0x69, 0x64, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70,
	0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x70, 0x75, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x63, 0x70, 0x75, 0x50, 0x65, 0x72, 0x63, 0x65,
	0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x73, 0x73, 0x4b, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x05, 0x72, 0x73, 0x73, 0x4b, 0x62, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x61, 0x64,
	0x4b, 0x62, 0x50, 0x65, 0x72, 0x53, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x72, 0x65,
	0x61, 0x64, 0x4b, 0x62, 0x50, 0x65, 0x72, 0x53, 0x12, 0x20, 0x0a, 0x0b, 0x77, 0x72, 0x69, 0x74,
	0x65, 0x4b, 0x62, 0x50, 0x65, 0x72, 0x53, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x77,
	0x72, 0x69, 0x74, 0x65, 0x4b, 0x62, 0x50, 0x65, 0x72, 0x53, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x6d, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x6d, 0x6d, 0x22, 0x46,
	0x0a, 0x0d, 0x41, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x65, 0x6d,
	0x70, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x61, 0x74, 0x74,
	0x65, 0x6d, 0x70, 0x74, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x22, 0xff, 0x01, 0x0a, 0x09, 0x43, 0x6f, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1a,
	0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x0f,
	0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x53, 0x73, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x75, 0x73, 0x65, 0x53,
	0x73, 0x6c, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6d, 0x69, 0x6e, 0x69, 0x2d, 0x64, 0x72, 0x6f, 0x70, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_common_proto_rawDescOnce sync.Once
	file_common_proto_common_proto_rawDescData = file_common_proto_common_proto_rawDesc
)

func file_common_proto_common_proto_rawDescGZIP() []byte {
	file_common_proto_common_proto_rawDescOnce.Do(func() {
		file_common_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_common_proto_rawDescData)
	})
	return file_common_proto_common_proto_rawDescData
}

var file_common_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_proto_common_proto_goTypes = []interface{}{
	(*PidStats)(nil),      // 0: common.PidStats
	(*AttemptStatus)(nil), // 1: common.AttemptStatus
	(*File)(nil),          // 2: common.File
	(*CosConfig)(nil),     // 3: common.CosConfig
}
var file_common_proto_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_common_proto_init() }
func file_common_proto_common_proto_init() {
	if File_common_proto_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_proto_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PidStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttemptStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CosConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_common_proto_goTypes,
		DependencyIndexes: file_common_proto_common_proto_depIdxs,
		MessageInfos:      file_common_proto_common_proto_msgTypes,
	}.Build()
	File_common_proto_common_proto = out.File
	file_common_proto_common_proto_rawDesc = nil
	file_common_proto_common_proto_goTypes = nil
	file_common_proto_common_proto_depIdxs = nil
}
