// ============================================================
// hotmethod.proto — 任务协议（最核心！）
// ============================================================
// 小白理解：定义了"任务长什么样"和"结果长什么样"
// Server 通过 Collect 给 Agent 派任务
// Agent 通过 NotifyResult 把结果回报给 Server
// ============================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: common/proto/hotmethod.proto

package hotmethod

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	common "github.com/mini-drop/apiserver/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ----------------------------------------------------------
// TaskDesc：一个完整的任务描述
// 就像外卖订单：点什么（采样参数）、送到哪（目标进程）、用啥工具（采集器类型）
// ----------------------------------------------------------
type TaskDesc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskID         string            `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`                                           // 任务唯一 ID，比如 "task-abc123"
	TaskType       uint32            `protobuf:"varint,2,opt,name=taskType,proto3" json:"taskType,omitempty"`                                      // 任务类型：0=通用CPU 1=Java 2=追踪 4=内存 6=Java堆
	ProfilerType   uint32            `protobuf:"varint,3,opt,name=profilerType,proto3" json:"profilerType,omitempty"`                              // 采集器：0=perf 1=async-profiler 2=pprof 3=eBPF
	SampleArgv     *RecordArgv       `protobuf:"bytes,4,opt,name=sampleArgv,proto3" json:"sampleArgv,omitempty"`                                   // 采样参数（频率、时长、目标PID）
	ContainerName  string            `protobuf:"bytes,5,opt,name=containerName,proto3" json:"containerName,omitempty"`                             // 容器名（如果是容器环境）
	ContainerType  uint32            `protobuf:"varint,6,opt,name=containerType,proto3" json:"containerType,omitempty"`                            // 容器类型
	TimeoutSec     uint32            `protobuf:"varint,7,opt,name=timeoutSec,proto3" json:"timeoutSec,omitempty"`                                  // 超时时间（秒），超过就认为失败
	CosConfig      *common.CosConfig `protobuf:"bytes,8,opt,name=cosConfig,proto3" json:"cosConfig,omitempty"`                                     // 上传结果的存储配置
	ScriptContent  string            `protobuf:"bytes,9,opt,name=scriptContent,proto3" json:"scriptContent,omitempty"`                             // 脚本内容（ScriptExec 类型任务用）
	PprofUrl       string            `protobuf:"bytes,10,opt,name=pprofUrl,proto3" json:"pprofUrl,omitempty"`                                      // Go pprof 完整 profile URL（profilerType=2）
	RequestId      string            `protobuf:"bytes,11,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                   // API 请求 ID，用于日志串联
	AttemptId      uint64            `protobuf:"varint,12,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`                  // 本次执行尝试 ID
	DeadlineUnixMs int64             `protobuf:"varint,13,opt,name=deadline_unix_ms,json=deadlineUnixMs,proto3" json:"deadline_unix_ms,omitempty"` // 任务截止时间（毫秒时间戳）
	ResourceBudget string            `protobuf:"bytes,14,opt,name=resource_budget,json=resourceBudget,proto3" json:"resource_budget,omitempty"`    // JSON 编码的资源预算
	TaskKind       string            `protobuf:"bytes,15,opt,name=task_kind,json=taskKind,proto3" json:"task_kind,omitempty"`                      // TaskKind 单一契约 ID
	ErrorCode      string            `protobuf:"bytes,16,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`                   // 下发前已知的稳定错误码（可选）
	// Types that are assignable to Payload:
	//	*TaskDesc_PerfPayload
	//	*TaskDesc_PprofPayload
	//	*TaskDesc_EbpfPayload
	Payload isTaskDesc_Payload `protobuf_oneof:"payload"`
}

func (x *TaskDesc) Reset() {
	*x = TaskDesc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_hotmethod_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDesc) ProtoMessage() {}

func (x *TaskDesc) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_hotmethod_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDesc.ProtoReflect.Descriptor instead.
func (*TaskDesc) Descriptor() ([]byte, []int) {
	return file_common_proto_hotmethod_proto_rawDescGZIP(), []int{0}
}

func (x *TaskDesc) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *TaskDesc) GetTaskType() uint32 {
	if x != nil {
		return x.TaskType
	}
	return 0
}

func (x *TaskDesc) GetProfilerType() uint32 {
	if x != nil {
		return x.ProfilerType
	}
	return 0
}

func (x *TaskDesc) GetSampleArgv() *RecordArgv {
	if x != nil {
		return x.SampleArgv
	}
	return nil
}

func (x *TaskDesc) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *TaskDesc) GetContainerType() uint32 {
	if x != nil {
		return x.ContainerType
	}
	return 0
}

func (x *TaskDesc) GetTimeoutSec() uint32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

func (x *TaskDesc) GetCosConfig() *common.CosConfig {
	if x != nil {
		return x.CosConfig
	}
	return nil
}

func (x *TaskDesc) GetScriptContent() string {
	if x != nil {
		return x.ScriptContent
	}
	return ""
}

func (x *TaskDesc) GetPprofUrl() string {
	if x != nil {
		return x.PprofUrl
	}
	return ""
}

func (x *TaskDesc) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TaskDesc) GetAttemptId() uint64 {
	if x != nil {
		return x.AttemptId
	}
	return 0
}

func (x *TaskDesc) GetDeadlineUnixMs() int64 {
	if x != nil {
		return x.DeadlineUnixMs
	}
	return 0
}

func (x *TaskDesc) GetResourceBudget() string {
	if x != nil {
		return x.ResourceBudget
	}
	return ""
}

func (x *TaskDesc) GetTaskKind() string {
	if x != nil {
		return x.TaskKind
	}
	return ""
}

func (x *TaskDesc) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (m *TaskDesc) GetPayload() isTaskDesc_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *TaskDesc) GetPerfPayload() *PerfPayload {
	if x, ok := x.GetPayload().(*TaskDesc_PerfPayload); ok {
		return x.PerfPayload
	}
	return nil
}

func (x *TaskDesc) GetPprofPayload() *PprofPayload {
	if x, ok := x.GetPayload().(*TaskDesc_PprofPayload); ok {
		return x.PprofPayload
	}
	return nil
}

func (x *TaskDesc) GetEbpfPayload() *EBpfPayload {
	if x, ok := x.GetPayload().(*TaskDesc_EbpfPayload); ok {
		return x.EbpfPayload
	}
	return nil
}

type isTaskDesc_Payload interface {
	isTaskDesc_Payload()
}

type TaskDesc_PerfPayload struct {
	PerfPayload *PerfPayload `protobuf:"bytes,17,opt,name=perf_payload,json=perfPayload,proto3,oneof"`
}

type TaskDesc_PprofPayload struct {
	PprofPayload *PprofPayload `protobuf:"bytes,18,opt,name=pprof_payload,json=pprofPayload,proto3,oneof"`
}

type TaskDesc_EbpfPayload struct {
	EbpfPayload *EBpfPayload `protobuf:"bytes,19,opt,name=ebpf_payload,json=ebpfPayload,proto3,oneof"`
}

func (*TaskDesc_PerfPayload) isTaskDesc_Payload() {}

func (*TaskDesc_PprofPayload) isTaskDesc_Payload() {}

func (*TaskDesc_EbpfPayload) isTaskDesc_Payload() {}

// ----------------------------------------------------------
// RecordArgv：采样参数（相当于 perf record 的命令行参数）
// ----------------------------------------------------------
type RecordArgv struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hz         uint32 `protobuf:"varint,1,opt,name=hz,proto3" json:"hz,omitempty"`                 // 采样频率，比如 99 表示每秒采样 99 次
	Duration   uint64 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`     // 采集时长（秒），比如 10 表示采 10 秒
	Pid        int32  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`               // 目标进程 PID
	Callgraph  string `protobuf:"bytes,4,opt,name=callgraph,proto3" json:"callgraph,omitempty"`    // 调用图方式：fp(帧指针) / dwarf / lbr
	Subprocess bool   `protobuf:"varint,5,opt,name=subprocess,proto3" json:"subprocess,omitempty"` // 是否包含子进程
	Event      string `protobuf:"bytes,6,opt,name=event,proto3" json:"event,omitempty"`            // 采样事件：cpu-cycles / cache-misses / ...
}

func (x *RecordArgv) Reset() {
	*x = RecordArgv{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_hotmethod_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordArgv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordArgv) ProtoMessage() {}

func (x *RecordArgv) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_hotmethod_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordArgv.ProtoReflect.Descriptor instead.
func (*RecordArgv) Descriptor() ([]byte, []int) {
	return file_common_proto_hotmethod_proto_rawDescGZIP(), []int{1}
}

func (x *RecordArgv) GetHz() uint32 {
	if x != nil {
		return x.Hz
	}
	return 0
}

func (x *RecordArgv) GetDuration() uint64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *RecordArgv) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *RecordArgv) GetCallgraph() string {
	if x != nil {
		return x.Callgraph
	}
	return ""
}

func (x *RecordArgv) GetSubprocess() bool {
	if x != nil {
		return x.Subprocess
	}
	return false
}

func (x *RecordArgv) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

type PerfPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Argv *RecordArgv `protobuf:"bytes,1,opt,name=argv,proto3" json:"argv,omitempty"`
}

func (x *PerfPayload) Reset() {
	*x = PerfPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_hotmethod_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PerfPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerfPayload) ProtoMessage() {}

func (x *PerfPayload) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_hotmethod_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerfPayload.ProtoReflect.Descriptor instead.
func (*PerfPayload) Descriptor() ([]byte, []int) {
	return file_common_proto_hotmethod_proto_rawDescGZIP(), []int{2}
}

func (x *PerfPayload) GetArgv() *RecordArgv {
	if x != nil {
		return x.Argv
	}
	return nil
}

type PprofPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url      string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Duration uint64 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *PprofPayload) Reset() {
	*x = PprofPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_hotmethod_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PprofPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PprofPayload) ProtoMessage() {}

func (x *PprofPayload) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_hotmethod_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PprofPayload.ProtoReflect.Descriptor instead.
func (*PprofPayload) Descriptor() ([]byte, []int) {
	return file_common_proto_hotmethod_proto_rawDescGZIP(), []int{3}
}

func (x *PprofPayload) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PprofPayload) GetDuration() uint64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type EBpfPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode     string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Duration uint64 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Pid      int32  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
}

func (x *EBpfPayload) Reset() {
	*x = EBpfPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_hotmethod_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EBpfPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EBpfPayload) ProtoMessage() {}

func (x *EBpfPayload) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_hotmethod_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EBpfPayload.ProtoReflect.Descriptor instead.
func (*EBpfPayload) Descriptor() ([]byte, []int) {
	return file_common_proto_hotmethod_proto_rawDescGZIP(), []int{4}
}

func (x *EBpfPayload) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *EBpfPayload) GetDuration() uint64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *EBpfPayload) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// ----------------------------------------------------------
// TaskResult：Agent 采集完成后回报的结果
// ----------------------------------------------------------
type TaskResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskID         string             `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`                 // 对应哪个任务
	ErrorMessage   string             `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`     // 错误信息，空字符串 = 成功
	File           *common.File       `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`                     // 小文件直接内嵌在消息里
	CosKey         string             `protobuf:"bytes,4,opt,name=cosKey,proto3" json:"cosKey,omitempty"`                 // 大文件上传到存储后的 key（路径）
	SelfPstats     []*common.PidStats `protobuf:"bytes,5,rep,name=selfPstats,proto3" json:"selfPstats,omitempty"`         // Agent 自身资源历史
	ChildrenPstats []*common.PidStats `protobuf:"bytes,6,rep,name=childrenPstats,proto3" json:"childrenPstats,omitempty"` // 子进程资源历史
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_hotmethod_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_hotmethod_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_common_proto_hotmethod_proto_rawDescGZIP(), []int{5}
}

func (x *TaskResult) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *TaskResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskResult) GetFile() *common.File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *TaskResult) GetCosKey() string {
	if x != nil {
		return x.CosKey
	}
	return ""
}

func (x *TaskResult) GetSelfPstats() []*common.PidStats {
	if x != nil {
		return x.SelfPstats
	}
	return nil
}

func (x *TaskResult) GetChildrenPstats() []*common.PidStats {
	if x != nil {
		return x.ChildrenPstats
	}
	return nil
}

// ----------------------------------------------------------
// Target：目标机器（用 IP 地址标识）
// ----------------------------------------------------------
type Target struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"` // 目标 IP，比如 "192.168.1.100"
}

func (x *Target) Reset() {
	*x = Target{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_hotmethod_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_hotmethod_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_common_proto_hotmethod_proto_rawDescGZIP(), []int{6}
}

func (x *Target) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

var File_common_proto_hotmethod_proto protoreflect.FileDescriptor

var file_common_proto_hotmethod_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68,
	0x6f, 0x74, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x68, 0x6f, 0x74, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x8a, 0x06, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x65, 0x73, 0x63, 0x12, 0x16,
	0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x74, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x41, 0x72, 0x67, 0x76, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x68, 0x6f, 0x74,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x41, 0x72, 0x67,
	0x76, 0x52, 0x0a, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x41, 0x72, 0x67, 0x76, 0x12, 0x24, 0x0a,
	0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74,
	0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x63, 0x12, 0x2f, 0x0a, 0x09, 0x63, 0x6f, 0x73,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x09, 0x63, 0x6f, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x70, 0x72, 0x6f, 0x66, 0x55, 0x72, 0x6c, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x70, 0x72, 0x6f, 0x66, 0x55, 0x72, 0x6c, 0x12, 0x1d, 0x0a, 0x0a,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61,
	0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x09, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x64, 0x65,
	0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x73, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x6e,
	0x69, 0x78, 0x4d, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x5f, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x70, 0x65, 0x72,
	0x66, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x68, 0x6f, 0x74, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x2e, 0x50, 0x65, 0x72, 0x66,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x00, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x66, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x3e, 0x0a, 0x0d, 0x70, 0x70, 0x72, 0x6f, 0x66, 0x5f,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x68, 0x6f, 0x74, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x2e, 0x50, 0x70, 0x72, 0x6f, 0x66, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x00, 0x52, 0x0c, 0x70, 0x70, 0x72, 0x6f, 0x66, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x3b, 0x0a, 0x0c, 0x65, 0x62, 0x70, 0x66, 0x5f, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x13, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x68,
	0x6f, 0x74, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x2e, 0x45, 0x42, 0x70, 0x66, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x48, 0x00, 0x52, 0x0b, 0x65, 0x62, 0x70, 0x66, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x9e,
	0x01, 0x0a, 0x0a, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x41, 0x72, 0x67, 0x76, 0x12, 0x0e, 0x0a,
	0x02, 0x68, 0x7a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x68, 0x7a, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x61, 0x6c, 0x6c, 0x67, 0x72, 0x61, 0x70, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x61, 0x6c, 0x6c, 0x67, 0x72, 0x61, 0x70, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x75, 0x62,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x73,
	0x75, 0x62, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22,
	0x38, 0x0a, 0x0b, 0x50, 0x65, 0x72, 0x66, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x29,
	0x0a, 0x04, 0x61, 0x72, 0x67, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x68,
	0x6f, 0x74, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x41,
	0x72, 0x67, 0x76, 0x52, 0x04, 0x61, 0x72, 0x67, 0x76, 0x22, 0x3c, 0x0a, 0x0c, 0x50, 0x70, 0x72,
	0x6f, 0x66, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4f, 0x0a, 0x0b, 0x45, 0x42, 0x70, 0x66, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64, 0x22, 0xee, 0x01, 0x0a, 0x0a, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x12,
	0x22, 0x0a, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x73, 0x4b, 0x65, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x30, 0x0a,
	0x0a, 0x73, 0x65, 0x6c, 0x66, 0x50, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x69, 0x64, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x52, 0x0a, 0x73, 0x65, 0x6c, 0x66, 0x50, 0x73, 0x74, 0x61, 0x74, 0x73, 0x12,
	0x38, 0x0a, 0x0e, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x50, 0x73, 0x74, 0x61, 0x74,
	0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x50, 0x69, 0x64, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x0e, 0x63, 0x68, 0x69, 0x6c, 0x64,
	0x72, 0x65, 0x6e, 0x50, 0x73, 0x74, 0x61, 0x74, 0x73, 0x22, 0x18, 0x0a, 0x06, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x70, 0x32, 0x80, 0x01, 0x0a, 0x09, 0x48, 0x6f, 0x74, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x12, 0x34, 0x0a, 0x07, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x12, 0x11, 0x2e, 0x68,
	0x6f, 0x74, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3d, 0x0a, 0x0c, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x15, 0x2e, 0x68, 0x6f, 0x74, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x6e, 0x69, 0x2d, 0x64, 0x72, 0x6f, 0x70, 0x2f, 0x61,
	0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68,
	0x6f, 0x74, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_hotmethod_proto_rawDescOnce sync.Once
	file_common_proto_hotmethod_proto_rawDescData = file_common_proto_hotmethod_proto_rawDesc
)

func file_common_proto_hotmethod_proto_rawDescGZIP() []byte {
	file_common_proto_hotmethod_proto_rawDescOnce.Do(func() {
		file_common_proto_hotmethod_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_hotmethod_proto_rawDescData)
	})
	return file_common_proto_hotmethod_proto_rawDescData
}

var file_common_proto_hotmethod_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_common_proto_hotmethod_proto_goTypes = []interface{}{
	(*TaskDesc)(nil),         // 0: hotmethod.TaskDesc
	(*RecordArgv)(nil),       // 1: hotmethod.RecordArgv
	(*PerfPayload)(nil),      // 2: hotmethod.PerfPayload
	(*PprofPayload)(nil),     // 3: hotmethod.PprofPayload
	(*EBpfPayload)(nil),      // 4: hotmethod.EBpfPayload
	(*TaskResult)(nil),       // 5: hotmethod.TaskResult
	(*Target)(nil),           // 6: hotmethod.Target
	(*common.CosConfig)(nil), // 7: common.CosConfig
	(*common.File)(nil),      // 8: common.File
	(*common.PidStats)(nil),  // 9: common.PidStats
	(*empty.Empty)(nil),      // 10: google.protobuf.Empty
}
var file_common_proto_hotmethod_proto_depIdxs = []int32{
	1,  // 0: hotmethod.TaskDesc.sampleArgv:type_name -> hotmethod.RecordArgv
	7,  // 1: hotmethod.TaskDesc.cosConfig:type_name -> common.CosConfig
	2,  // 2: hotmethod.TaskDesc.perf_payload:type_name -> hotmethod.PerfPayload
	3,  // 3: hotmethod.TaskDesc.pprof_payload:type_name -> hotmethod.PprofPayload
	4,  // 4: hotmethod.TaskDesc.ebpf_payload:type_name -> hotmethod.EBpfPayload
	1,  // 5: hotmethod.PerfPayload.argv:type_name -> hotmethod.RecordArgv
	8,  // 6: hotmethod.TaskResult.file:type_name -> common.File
	9,  // 7: hotmethod.TaskResult.selfPstats:type_name -> common.PidStats
	9,  // 8: hotmethod.TaskResult.childrenPstats:type_name -> common.PidStats
	6,  // 9: hotmethod.Hotmethod.Collect:input_type -> hotmethod.Target
	5,  // 10: hotmethod.Hotmethod.NotifyResult:input_type -> hotmethod.TaskResult
	10, // 11: hotmethod.Hotmethod.Collect:output_type -> google.protobuf.Empty
	10, // 12: hotmethod.Hotmethod.NotifyResult:output_type -> google.protobuf.Empty
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_common_proto_hotmethod_proto_init() }
func file_common_proto_hotmethod_proto_init() {
	if File_common_proto_hotmethod_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_proto_hotmethod_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskDesc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_hotmethod_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordArgv); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_hotmethod_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PerfPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_hotmethod_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PprofPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_hotmethod_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EBpfPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_hotmethod_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_hotmethod_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Target); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_common_proto_hotmethod_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*TaskDesc_PerfPayload)(nil),
		(*TaskDesc_PprofPayload)(nil),
		(*TaskDesc_EbpfPayload)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_hotmethod_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_hotmethod_proto_goTypes,
		DependencyIndexes: file_common_proto_hotmethod_proto_depIdxs,
		MessageInfos:      file_common_proto_hotmethod_proto_msgTypes,
	}.Build()
	File_common_proto_hotmethod_proto = out.File
	file_common_proto_hotmethod_proto_rawDesc = nil
	file_common_proto_hotmethod_proto_goTypes = nil
	file_common_proto_hotmethod_proto_depIdxs = nil
}
